---
title: "Week 3 Assignment"
author: "Marcelo Nardelli"
date: "15/02/2020"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introduction

We will use plotly to build a simple Boxplot for the mtcars dataset

```{r, message=FALSE,echo=TRUE}
library(plotly)
```


## Dataset preprocessing

```{r, message=FALSE,echo=TRUE}
mtcars$am <- as.factor(mtcars$am)
mtcars$vs <- as.factor(mtcars$vs)
levels(mtcars$am) <- c("automatic", "manual")
levels(mtcars$vs) <- c("v-shaped", "straight")
head(mtcars %>% select(mpg, am, vs))
```

## Generating the plot

```{r, message=FALSE,echo=TRUE}
title <- "Miles per Gallon by Transimission and Engine type"
x_title <- "Engine type"
y_title <- "Miles per Gallon"
legend_title <- "Transmission type"
p <- plot_ly(data = mtcars, x = ~vs, y = ~mpg, color = ~am, 
             type = "box") %>%
  layout(boxmode = "group", title = title, 
         xaxis = list(title = x_title),
         yaxis = list(title = y_title), 
         legend = list(title = list(text = legend_title)))
```

## Interactive Plot

```{r, echo=FALSE, warning=FALSE}
p
``` 

## End